import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
console.log('launch');const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1200,height:800}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);console.log('navigate');await page.goto('http://localhost:5173');console.log('start');await page.click('#play');await page.waitForTimeout(300);let before=await page.evaluate(()=>window.__game.world.player.x);await page.keyboard.down('d');await page.keyboard.down('Shift');await page.waitForTimeout(500);await page.keyboard.up('d');await page.keyboard.up('Shift');assert(await page.evaluate(()=>window.__game.world.player.x)>before);assert(await page.evaluate(()=>window.__game.world.stamina)<100);await page.keyboard.press('Escape');const time=await page.evaluate(()=>window.__game.world.time);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__game.world.time),time);await page.click('#resume');
// Controlled encounters exercise renderer, feedback and menus without random AI timing.
console.log('collisions');for(const kind of ['blue','ref']){await page.evaluate(kind=>{const w=window.__game.world;w.cooldown=0;const a=w.obstacles.find(a=>a.kind===kind);a.x=w.player.x;a.y=w.player.y;},kind);await page.waitForTimeout(100);assert(await page.evaluate(()=>window.__game.world.cooldown)>0);}
await page.evaluate(()=>{const w=window.__game.world;w.time=4;w.obstacles=[];const s=w.stewards[0];s.warning=0;s.x=w.player.x;s.y=w.player.y;});console.log('capture');await page.waitForSelector('#results:not([hidden])');assert(Number(await page.evaluate(()=>localStorage.getItem('pi-best')))>0);for(let i=0;i<3;i++){await page.click(i===0?'#retry':'#restart');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__game.world.obstacles.length),23);assert.equal(await page.evaluate(()=>window.__game.world.stewards.length),2);}await page.click('#resume');await page.setViewportSize({width:390,height:844});await page.waitForSelector('#rotate:not([hidden])');assert.equal(await page.evaluate(()=>window.__game.world.running),false);await page.setViewportSize({width:844,height:390});await page.click('#resume');
console.log('touch');
// Independent pointers, cancellation, sprint and normalized joystick state.
const cdp=await context.newCDPSession(page);const jb=await page.locator('#joystick').boundingBox(),sb=await page.locator('#sprint').boundingBox();const jx=jb.x+jb.width/2,jy=jb.y+jb.height/2,sx=sb.x+sb.width/2,sy=sb.y+sb.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:jx,y:jy,id:1},{x:sx,y:sy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:jx+25,y:jy-10,id:1},{x:sx,y:sy,id:2}]});assert(await page.evaluate(()=>window.__game.controls.sprint));assert(await page.evaluate(()=>window.__game.controls.x)>0);await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await page.evaluate(()=>window.__game.controls.sprint),false);assert.equal(await page.evaluate(()=>window.__game.controls.x),0);await page.keyboard.press('Escape');await page.click('.home:visible');await page.setViewportSize({width:1200,height:800});await page.screenshot({path:'screenshot.png'});assert.deepEqual(errors,[]);await context.close();
const offlineContext=await browser.newContext();const prod=await offlineContext.newPage();await prod.goto('http://localhost:4173');await prod.waitForFunction(()=>document.querySelector('#footer-status').dataset.status==='offline');await prod.evaluate(()=>navigator.serviceWorker.ready);await prod.reload();await offlineContext.setOffline(true);await prod.reload();await prod.waitForSelector('canvas');await prod.click('#play');await prod.waitForTimeout(500);assert.equal(await prod.locator('#menu').isVisible(),false);await offlineContext.close();await browser.close();console.log('PASS: desktop flow, sprint, pause, collisions, capture, saved best, retries, orientation, independent pointer cancellation, offline reload.');
