export class Sound {
 enabled=true;ctx:AudioContext|null=null;private bed:AudioBufferSourceNode|null=null;private bedGain:GainNode|null=null;private master:GainNode|null=null;private filter:BiquadFilterNode|null=null;private effects=new Set<AudioScheduledSourceNode>();private lastBeat=-1;
 unlock(){if(!this.enabled)return;try{this.ctx??=new AudioContext();this.master??=this.ctx.createGain();this.master.connect(this.ctx.destination);void this.ctx.resume().catch(()=>{});}catch{/* Audio remains optional. */}}
 private noise(seconds:number){const c=this.ctx!,buffer=c.createBuffer(1,Math.ceil(c.sampleRate*seconds),c.sampleRate),data=buffer.getChannelData(0);let previous=0;for(let i=0;i<data.length;i++){previous=(previous+(Math.random()*2-1)*.1)/1.1;data[i]=previous*3;}return buffer;}
 private track(source:AudioScheduledSourceNode){this.effects.add(source);source.onended=()=>{source.disconnect();this.effects.delete(source);};}
 private tone(frequency:number,end:number,duration:number,volume:number,type:OscillatorType='triangle',delay=0){const c=this.ctx!,o=c.createOscillator(),g=c.createGain(),at=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(frequency,at);o.frequency.exponentialRampToValueAtTime(end,at+duration);g.gain.setValueAtTime(volume,at);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(this.master!);this.track(o);o.start(at);o.stop(at+duration+.02);}
 private cheer(){const c=this.ctx!,source=c.createBufferSource(),filter=c.createBiquadFilter(),gain=c.createGain();source.buffer=this.noise(1.2);filter.type='bandpass';filter.frequency.value=850;filter.Q.value=.7;const at=c.currentTime;gain.gain.setValueAtTime(.01,at);gain.gain.linearRampToValueAtTime(.32,at+.12);gain.gain.exponentialRampToValueAtTime(.001,at+1.15);source.connect(filter);filter.connect(gain);gain.connect(this.master!);this.track(source);source.start();source.stop(at+1.2);for(const [index,f] of [440,550,660].entries())this.tone(f,f*1.12,.55,.025,'sine',index*.04);}
 play(kind:string){if(!this.enabled||!this.ctx||!this.master)return;try{switch(kind){case 'cheer':this.tone(100,40,.18,.15);this.cheer();break;case 'arrival':this.tone(1100,900,.12,.07,'square');this.tone(1400,1100,.12,.05,'square',.16);break;case 'kick':this.tone(150,45,.15,.13);break;case 'whistle':this.tone(1700,2200,.22,.08,'sine');break;case 'capture':this.tone(180,65,.4,.1);break;case 'near':this.tone(620,900,.2,.06);break;default:this.tone(110,40,.22,.14);}}catch{}}
 update(running:boolean,time:number){if(!this.enabled||!running){this.stopBackground();if(!this.enabled)this.stopEffects();if(this.master)this.master.gain.value=this.enabled?1:0;return;}if(!this.ctx||!this.master||this.ctx.state!=='running')return;try{this.master.gain.value=1;if(!this.bed){const source=this.ctx.createBufferSource();source.buffer=this.noise(3);source.loop=true;this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.bedGain=this.ctx.createGain();this.bedGain.gain.value=0;source.connect(this.filter);this.filter.connect(this.bedGain);this.bedGain.connect(this.master);source.start();this.bed=source;this.lastBeat=-1;}
 const drama=Math.min(1,time/75);this.bedGain!.gain.setTargetAtTime(.035+drama*.085,this.ctx.currentTime,.2);this.filter!.frequency.setTargetAtTime(450+drama*950,this.ctx.currentTime,.3);
 // Beat count is tied to simulation time, so pausing also freezes the rhythm.
 const beat=Math.floor(.8*time+Math.min(time,75)**2/360+Math.max(0,time-75)*75/180);if(beat!==this.lastBeat){this.lastBeat=beat;this.tone(80+drama*25,35,.16,.025+drama*.04,'sine');if(drama>.35&&beat%4===0)this.tone(220,160,.18,.025);}
 }catch{this.stopBackground();}}
 stopBackground(){try{this.bed?.stop();this.bed?.disconnect();this.filter?.disconnect();this.bedGain?.disconnect();}catch{}this.bed=null;this.bedGain=null;this.filter=null;this.lastBeat=-1;}
 stopEffects(){for(const source of this.effects){try{source.stop();}catch{}}this.effects.clear();}
 pause(){this.stopBackground();this.stopEffects();}
}
