export class Controls{
 keys=new Set<string>();x=0;y=0;sprint=false;moveId:number|null=null;sprintId:number|null=null;origin={x:0,y:0};onPause=()=>{};
 constructor(){const joy=document.querySelector<HTMLElement>('#joystick')!,stick=document.querySelector<HTMLElement>('#stick')!,sprint=document.querySelector<HTMLElement>('#sprint')!;
 window.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&e.target.closest('select,input,textarea,[contenteditable]'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();this.keys.add(e.key.toLowerCase());if(e.key==='Escape'&&!e.repeat)this.onPause();});window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));
 joy.addEventListener('pointerdown',e=>{if(this.moveId!==null)return;this.moveId=e.pointerId;this.origin={x:e.clientX,y:e.clientY};joy.setPointerCapture(e.pointerId);joy.classList.add('active');});joy.addEventListener('pointermove',e=>{if(e.pointerId!==this.moveId)return;const dx=e.clientX-this.origin.x,dy=e.clientY-this.origin.y,n=Math.max(36,Math.hypot(dx,dy));this.x=dx/n;this.y=dy/n;stick.style.transform=`translate(${this.x*30}px,${this.y*30}px)`;});
 const end=(e:PointerEvent)=>{if(e.pointerId===this.moveId){this.moveId=null;this.x=this.y=0;stick.style.transform='';joy.classList.remove('active');}};joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end);joy.addEventListener('lostpointercapture',end);
 sprint.addEventListener('pointerdown',e=>{if(this.sprintId!==null)return;this.sprintId=e.pointerId;this.sprint=true;sprint.setPointerCapture(e.pointerId);sprint.classList.add('active');});const stop=(e:PointerEvent)=>{if(e.pointerId===this.sprintId){this.sprintId=null;this.sprint=false;sprint.classList.remove('active');}};sprint.addEventListener('pointerup',stop);sprint.addEventListener('pointercancel',stop);sprint.addEventListener('lostpointercapture',stop);window.addEventListener('blur',()=>this.reset());}
 read(){return{x:this.x+Number(this.keys.has('d')||this.keys.has('arrowright'))-Number(this.keys.has('a')||this.keys.has('arrowleft')),y:this.y+Number(this.keys.has('s')||this.keys.has('arrowdown'))-Number(this.keys.has('w')||this.keys.has('arrowup')),sprint:this.sprint||this.keys.has('shift')};}
 reset(){this.keys.clear();this.x=this.y=0;this.sprint=false;this.moveId=this.sprintId=null;document.querySelector('#stick')!.removeAttribute('style');document.querySelectorAll('.active').forEach(e=>e.classList.remove('active'));}
}
