import {C} from './config';
import {initialiseLocale, languages, getLocale, setLocale, t, formatTime, formatNearMisses, translateDocument, type Locale, type MessageKey} from './i18n';
import Phaser from 'phaser';import {registerSW} from 'virtual:pwa-register';import './style.css';import {World} from './model';import {Controls} from './input';import {Stadium} from './scene';import {Sound} from './audio';import {load,save} from './storage';
initialiseLocale();
const el=(id:string)=>document.getElementById(id)!;const world=new World(),controls=new Controls(),sound=new Sound();let best=load('pi-best',0),state:'menu'|'play'|'pause'|'results'='menu',noticeUntil=0; sound.enabled=load('pi-sound',1)===1;
const scene=new Stadium(world,controls);new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1200,height:660,backgroundColor:'#173b3e',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[scene],render:{antialias:true},audio:{noAudio:true}});
function soundLabel(){el('sound').textContent=t(sound.enabled?'soundOn':'soundOff');el('sound').setAttribute('aria-pressed',String(sound.enabled));}soundLabel();

let noticeKey: MessageKey|null=null, footerKey: MessageKey='footer', installHelpKey: MessageKey|null=null, resultRecord=false;
function renderNotice(){el('notice').textContent=noticeKey?t(noticeKey,{seconds:C.headStart}):'';}
function renderResults(){el('score').textContent=formatTime(world.time);el('record').textContent=t(resultRecord?'record':'end');el('result-detail').textContent=t('result',{best:formatTime(best),near:formatNearMisses(world.near)});}
const languageSelect=el('language') as HTMLSelectElement;
for(const [value,label] of Object.entries(languages)){const option=document.createElement('option');option.value=value;option.textContent=label;languageSelect.append(option);}
function renderLanguage(){translateDocument();languageSelect.value=getLocale();soundLabel();renderNotice();renderResults();el('time').textContent=formatTime(world.time);el('best').textContent=formatTime(best);el('footer-status').textContent=t(footerKey);if(installHelpKey)el('install-help').textContent=t(installHelpKey);}
languageSelect.onchange=()=>{setLocale(languageSelect.value as Locale);renderLanguage();};
renderLanguage();

function show(next:typeof state){state=next;el('app').dataset.state=next;sound.update(next==='play',world.time);if(next==='pause'||next==='menu')sound.pause();for(const id of ['menu','paused','results'])el(id).hidden=id!==(next==='pause'?'paused':next);el('pause').hidden=next!=='play';controls.reset();world.running=next==='play';el('joystick').style.visibility=el('sprint').style.visibility=next==='play'?'visible':'hidden';}
function start(){sound.unlock();world.reset();show('play');noticeKey='headStart';renderNotice();noticeUntil=C.headStart;}
function pause(){if(state==='play'){show('pause');noticeKey=null;renderNotice();}}controls.onPause=()=>state==='pause'?resume():pause();
function resume(){if(document.hidden||innerHeight>innerWidth)return;show('play');sound.unlock();}
world.onEvent=kind=>{sound.play(kind);if(kind==='capture'){const record=world.time>best;best=Math.max(best,world.time);save('pi-best',best);resultRecord=record;renderResults();show('results');el('retry').focus();}else if(kind!=='kick'){noticeKey=kind==='whistle'?'whistle':kind==='near'?'near':kind==='arrival'?'arrival':kind==='cheer'?'cheer':'bump';renderNotice();noticeUntil=world.time+1.2;}};
el('help').onclick=()=>{el('help-panel').hidden=false;el('help-close').focus();};el('help-close').onclick=()=>{el('help-panel').hidden=true;el('help').focus();};document.addEventListener('keydown',e=>{if(el('help-panel').hidden)return;if(e.key==='Escape'){e.stopPropagation();el('help-panel').hidden=true;el('help').focus();}if(e.key==='Tab'){e.preventDefault();el('help-close').focus();}});
el('play').onclick=start;el('retry').onclick=start;el('restart').onclick=start;el('resume').onclick=resume;el('pause').onclick=pause;document.querySelectorAll<HTMLButtonElement>('.home').forEach(b=>b.onclick=()=>show('menu'));el('sound').onclick=()=>{sound.enabled=!sound.enabled;save('pi-sound',Number(sound.enabled));sound.unlock();sound.update(world.running,world.time);soundLabel();};
function orientation(){const portrait=innerHeight>innerWidth;el('rotate').hidden=!portrait;if(portrait)pause();}window.addEventListener('resize',orientation);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});orientation();show('menu');
let canvasSize='';
function positionControls(){const canvas=document.querySelector('canvas');if(!canvas)return;const bounds=canvas.getBoundingClientRect(),arena=el('arena').getBoundingClientRect(),key=`${bounds.x},${bounds.y},${bounds.width},${bounds.height}`;if(key===canvasSize)return;canvasSize=key;const scale=bounds.width/C.width;el('pitch-controls').style.setProperty('--field-left',`${bounds.left-arena.left+C.pitch.left*scale}px`);el('pitch-controls').style.setProperty('--field-right',`${arena.right-bounds.left-C.pitch.right*scale}px`);el('pitch-controls').style.setProperty('--field-bottom',`${arena.bottom-bounds.top-C.pitch.bottom*scale}px`);}
let lastHud=-1,lastBest=-1;scene.onTick=()=>{positionControls();sound.update(world.running,world.time);const t=Math.floor(world.time*10);if(t!==lastHud){el('time').textContent=formatTime(world.time);lastHud=t;}if(best!==lastBest){el('best').textContent=formatTime(best);lastBest=best;}const meter=el('stamina') as HTMLMeterElement;if(Math.abs(meter.value-world.stamina)>1)meter.value=world.stamina;if(state==='play'&&world.time>noticeUntil&&noticeKey){noticeKey=null;renderNotice();}};
let installEvent:Event&{prompt:()=>Promise<void>;userChoice:Promise<unknown>}|null=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e as typeof installEvent;});el('install').onclick=async()=>{if(installEvent){await installEvent.prompt();await installEvent.userChoice;installEvent=null;}else{el('help-panel').hidden=false;el('install-help').hidden=false;el('help-close').focus();installHelpKey=/iPhone|iPad/.test(navigator.userAgent)?'installSafari':'installBrowser';el('install-help').textContent=t(installHelpKey);}};
registerSW({onOfflineReady(){footerKey='offline';el('footer-status').textContent=t(footerKey);el('footer-status').dataset.status='offline';},onNeedRefresh(){footerKey='update';el('footer-status').textContent=t(footerKey);el('footer-status').dataset.status='update';}});
// Development-only hook for reproducible browser verification. Removed by production bundling.
if(import.meta.env.DEV)(window as unknown as {__game:unknown}).__game={world,controls,sound,pause,resume,start};
