import Phaser from 'phaser';import {registerSW} from 'virtual:pwa-register';import './style.css';import {World} from './model';import {Controls} from './input';import {Stadium} from './scene';import {Sound} from './audio';import {load,save} from './storage';
const el=(id:string)=>document.getElementById(id)!;const world=new World(),controls=new Controls(),sound=new Sound();let best=load('pi-best',0),state:'menu'|'play'|'pause'|'results'='menu',noticeUntil=0; sound.enabled=load('pi-sound',1)===1;
const scene=new Stadium(world,controls);new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1200,height:660,backgroundColor:'#173b3e',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[scene],render:{antialias:true},audio:{noAudio:true}});
function soundLabel(){el('sound').textContent=`Sound: ${sound.enabled?'on':'off'}`;el('sound').setAttribute('aria-pressed',String(sound.enabled));}soundLabel();
function show(next:typeof state){state=next;for(const id of ['menu','paused','results'])el(id).hidden=id!==(next==='pause'?'paused':next);el('pause').hidden=next!=='play';controls.reset();world.running=next==='play';el('joystick').style.visibility=el('sprint').style.visibility=next==='play'?'visible':'hidden';}
function start(){sound.unlock();world.reset();show('play');el('notice').textContent='A 3-second head start. Make it count!';noticeUntil=3;}
function pause(){if(state==='play'){show('pause');el('notice').textContent='';}}controls.onPause=()=>state==='pause'?resume():pause();
function resume(){if(document.hidden||innerHeight>innerWidth)return;show('play');sound.unlock();}
world.onEvent=kind=>{sound.play(kind);if(kind==='capture'){const record=world.time>best;best=Math.max(best,world.time);save('pi-best',best);el('score').textContent=`${world.time.toFixed(1)}s`;el('record').textContent=record?'NEW PERSONAL BEST!':'END OF THE RUN';el('result-detail').textContent=`Best ${best.toFixed(1)}s · ${world.near} near ${world.near===1?'miss':'misses'}`;show('results');el('retry').focus();}else{el('notice').textContent=kind==='whistle'?'Ref says: absolutely not!':kind==='near'?'Close one! +1 near miss':'Watch the players!';noticeUntil=world.time+1.2;}};
el('play').onclick=start;el('retry').onclick=start;el('restart').onclick=start;el('resume').onclick=resume;el('pause').onclick=pause;document.querySelectorAll<HTMLButtonElement>('.home').forEach(b=>b.onclick=()=>show('menu'));el('sound').onclick=()=>{sound.enabled=!sound.enabled;save('pi-sound',Number(sound.enabled));sound.unlock();soundLabel();};
function orientation(){const portrait=innerHeight>innerWidth;el('rotate').hidden=!portrait;if(portrait)pause();}window.addEventListener('resize',orientation);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});orientation();show('menu');
let lastHud=-1,lastBest=-1;scene.onTick=()=>{const t=Math.floor(world.time*10);if(t!==lastHud){el('time').textContent=`${world.time.toFixed(1)}s`;lastHud=t;}if(best!==lastBest){el('best').textContent=`${best.toFixed(1)}s`;lastBest=best;}const meter=el('stamina') as HTMLMeterElement;if(Math.abs(meter.value-world.stamina)>1)meter.value=world.stamina;if(state==='play'&&world.time>noticeUntil)el('notice').textContent='';};
let installEvent:Event&{prompt:()=>Promise<void>;userChoice:Promise<unknown>}|null=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e as typeof installEvent;});el('install').onclick=async()=>{if(installEvent){await installEvent.prompt();await installEvent.userChoice;installEvent=null;}else{el('install-help').hidden=false;el('install-help').textContent=/iPhone|iPad/.test(navigator.userAgent)?'Safari: tap Share, then Add to Home Screen.':'Use your browser menu → Install app or Add to Home Screen. Installation needs HTTPS and browser support.';}};
registerSW({onOfflineReady(){el('footer-status').textContent='Ready for offline play.';},onNeedRefresh(){el('footer-status').textContent='Update available. Close all game tabs to update safely.';}});
// Development-only hook for reproducible browser verification. Removed by production bundling.
if(import.meta.env.DEV)(window as unknown as {__game:unknown}).__game={world,controls,pause,resume,start};
